from __future__ import annotations

import json
from collections.abc import Iterable
from dataclasses import dataclass
from enum import Enum
from typing import Any

from .freeze import canonical_sha256


class EvidenceClass(str, Enum):
    """Epistemic status for a statement carried through the toolkit.

    These classes intentionally separate facts measured in biological data from
    assumptions, predictions, fitted quantities, and states generated by a model.
    Renderers and claim logic should consume these labels rather than infer status
    from field names or visual context.
    """

    MEASURED_STRUCTURE = "measured_structure"
    MEASURED_PHYSIOLOGY = "measured_physiology"
    PREDICTED_ANNOTATION = "predicted_annotation"
    CROSS_DATASET_PRIOR = "cross_dataset_prior"
    MODEL_ASSUMPTION = "model_assumption"
    FITTED_PARAMETER = "fitted_parameter"
    MODELED_STATE = "modeled_state"
    BEHAVIORAL_OUTPUT = "behavioral_output"


@dataclass(frozen=True)
class EvidenceRecord:
    """One atomic, provenance-bearing statement.

    ``subject`` is deliberately generic. It may be a body ID, edge ID, population,
    experiment component, parameter, or run artifact. ``value`` must be JSON
    serializable so the complete ledger can be content addressed.
    """

    record_id: str
    subject: str
    predicate: str
    value: Any
    evidence_class: EvidenceClass
    authority: str
    dataset: str | None = None
    confidence: float | None = None
    provenance_ref: str | None = None
    notes: str | None = None

    def validate(self) -> None:
        if not self.record_id.strip():
            raise ValueError("evidence record_id must be non-empty")
        if not self.subject.strip():
            raise ValueError(f"evidence {self.record_id}: subject must be non-empty")
        if not self.predicate.strip():
            raise ValueError(f"evidence {self.record_id}: predicate must be non-empty")
        if not self.authority.strip():
            raise ValueError(f"evidence {self.record_id}: authority must be non-empty")
        if self.confidence is not None and not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"evidence {self.record_id}: confidence must be in [0, 1]")
        try:
            json.dumps(self.value, sort_keys=True, separators=(",", ":"))
        except (TypeError, ValueError) as exc:
            raise TypeError(
                f"evidence {self.record_id}: value must be JSON serializable"
            ) from exc

        if self.evidence_class in {
            EvidenceClass.MODELED_STATE,
            EvidenceClass.BEHAVIORAL_OUTPUT,
            EvidenceClass.FITTED_PARAMETER,
        } and not self.provenance_ref:
            raise ValueError(
                f"evidence {self.record_id}: {self.evidence_class.value} requires provenance_ref"
            )

    def to_dict(self) -> dict[str, Any]:
        self.validate()
        payload: dict[str, Any] = {
            "record_id": self.record_id,
            "subject": self.subject,
            "predicate": self.predicate,
            "value": self.value,
            "evidence_class": self.evidence_class.value,
            "authority": self.authority,
        }
        if self.dataset is not None:
            payload["dataset"] = self.dataset
        if self.confidence is not None:
            payload["confidence"] = self.confidence
        if self.provenance_ref is not None:
            payload["provenance_ref"] = self.provenance_ref
        if self.notes is not None:
            payload["notes"] = self.notes
        return payload

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> EvidenceRecord:
        record = cls(
            record_id=str(payload["record_id"]),
            subject=str(payload["subject"]),
            predicate=str(payload["predicate"]),
            value=payload.get("value"),
            evidence_class=EvidenceClass(payload["evidence_class"]),
            authority=str(payload["authority"]),
            dataset=payload.get("dataset"),
            confidence=payload.get("confidence"),
            provenance_ref=payload.get("provenance_ref"),
            notes=payload.get("notes"),
        )
        record.validate()
        return record


@dataclass(frozen=True)
class EvidenceLedger:
    """Immutable-by-convention set of evidence records with a canonical digest."""

    records: tuple[EvidenceRecord, ...]
    schema: str = "fly-sniff-evidence-ledger-v1"

    @classmethod
    def build(cls, records: Iterable[EvidenceRecord]) -> EvidenceLedger:
        ledger = cls(tuple(records))
        ledger.validate()
        return ledger

    def validate(self) -> None:
        if self.schema != "fly-sniff-evidence-ledger-v1":
            raise ValueError(f"unsupported evidence ledger schema: {self.schema}")
        seen: set[str] = set()
        for record in self.records:
            record.validate()
            if record.record_id in seen:
                raise ValueError(f"duplicate evidence record_id: {record.record_id}")
            seen.add(record.record_id)

    def _payload_without_hash(self) -> dict[str, Any]:
        self.validate()
        # Record order is not scientific content. Sort by stable record ID so two
        # independently assembled ledgers with the same statements hash identically.
        records = sorted(
            (record.to_dict() for record in self.records),
            key=lambda item: item["record_id"],
        )
        return {"schema": self.schema, "records": records}

    @property
    def sha256(self) -> str:
        return canonical_sha256(self._payload_without_hash())

    def to_dict(self) -> dict[str, Any]:
        payload = self._payload_without_hash()
        payload["ledger_sha256"] = self.sha256
        return payload

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> EvidenceLedger:
        ledger = cls.build(EvidenceRecord.from_dict(item) for item in payload.get("records", []))
        if payload.get("schema", ledger.schema) != ledger.schema:
            raise ValueError(f"unsupported evidence ledger schema: {payload.get('schema')}")
        claimed_hash = payload.get("ledger_sha256")
        if claimed_hash is not None and claimed_hash != ledger.sha256:
            raise ValueError("evidence ledger hash mismatch")
        return ledger

    def select(
        self,
        *,
        subject: str | None = None,
        predicate: str | None = None,
        evidence_class: EvidenceClass | None = None,
    ) -> tuple[EvidenceRecord, ...]:
        self.validate()
        return tuple(
            record
            for record in self.records
            if (subject is None or record.subject == subject)
            and (predicate is None or record.predicate == predicate)
            and (evidence_class is None or record.evidence_class is evidence_class)
        )
